export const SET_STORIES = 'SET_STORIES';

export const SET_POPULAR_STORIES = 'SET_POPULAR_STORIES';

export const SET_STORY = 'SET_STORY';

export const SET_ERROR = 'SET_ERROR';

export const SET_POPULAR_ERROR = 'SET_POPULAR_ERROR';

export const SET_STORY_ERROR = 'SET_STORY_ERROR';

export const SET_LOADING = 'SET_LOADING';

export const SET_LOADING_POPULAR = 'SET_LOADING_POPULAR';
